### ISSUE TITLE
Generation Issues of LiDAR Data under Snowy Conditions

### ISSUE THREAD

**Issue by Neko-coffee** [ika-rwth-aachen/MultiCorrupt#9]
Hello,
I'm trying to generate a dataset for snowy conditions and have encountered an issue while generating LiDAR data. I successfully generated the image data, but when generating the LiDAR data, I encountered the following error:

Traceback (most recent call last):
  File "/workspace/converter/lidar_converter.py", line 303, in <module>
    l = list(tqdm(pool.imap(sweep_map, range(length)), total=length))
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
AssertionError: Table lidarseg not found

However, I have included the "lidarseg" folder in the directory. Could there be an issue with the path?
![PixPin_2024-06-26_16-24-04](https://github.com/ika-rwth-aachen/MultiCorrupt/assets/129822131/dfed5dfa-ed41-4a97-a03d-8d1a473fecf8)

**Comment by TillBeemelmanns** [comment]
It seems that you are using Windows. I have not tested the code on Windows. Can you try to debug/print the path for the lidarseg directory and check if there is something wrong ?

I have time to debug the problem earliest end of the week.

Best,
Till

**Comment by TillBeemelmanns** [comment]
Could you please show which directories are inside your folder `lidarseg` ? Seems like you have not fully downloaded and installed `nuscenes-lidarseg`. Please refer to https://github.com/wzzheng/TPVFormer/issues/13

**Comment by Neko-coffee** [comment]
> Could you please show which directories are inside your folder `lidarseg` ? Seems like you have not fully downloaded and installed `nuscenes-lidarseg`. Please refer to [wzzheng/TPVFormer#13](https://github.com/wzzheng/TPVFormer/issues/13) and https://github.com/nutonomy/nuscenes-devkit/blob/4df2701feb3436ae49edaf70128488865a3f6ff9/python-sdk/nuscenes/nuscenes.py#L214您能否显示您的文件夹中有哪些目录 `lidarseg` ？似乎您还没有完全下载并安装 `nuscenes-lidarseg` .请参阅 [wzzheng/TPVFormer#13](https://github.com/wzzheng/TPVFormer/issues/13) 并 https://github.com/nutonomy/nuscenes-devkit/blob/4df2701feb3436ae49edaf70128488865a3f6ff9/python-sdk/nuscenes/nuscenes.py#L214

Thanks for your reply, due to my mistake I was missing the lidarseg.json in one of the folders, thanks again for your patience.
